### ISSUE TITLE
Pandas Version and Dependency

### ISSUE THREAD

**Issue by smatthews95** [UTFireResearch/hazard-analysis-dashboards#17]
The use of `pandas.json_normalize()` to flatten json-formatted incident data is causing an issue when deployed. Pandas didn't include that function until version 1.0.3. Version 0.25.2 is specified in `environment.yml` changing the specified version leads to a cascade of package conflicts.

Oddly, even with a fresh local conda environment created from `environment.yml` runs just fine without error. The reason is unclear.

**Comment by smatthews95** [comment]
@jtrejo13 Juan, I was wondering if you might be able to point me in the right direction on a couple things.

1) Is there a reason that you specified the particular package versions that you did? For one example, pandas 0.25.2 seems rather old.

2) What would you recommend to fix this? I don't have much experience with projects that require managing package versions or environments.

**Comment by jtrejo13** [comment]
@smatthews95 See my responses to your initial email. I'm happy to meet if you have any questions.

**Comment by smatthews95** [comment]
@jtrejo13  Thanks for the response. I was able to resolve it by just removing all the specific version requirements (except a couple places). I just wanted to make sure that I was messing up specifically chosen versions.
